### PR TITLE
Add method to access logger Fields

### PR DESCRIPTION
**Pull request by carlosms**
Needed by https://github.com/src-d/lookout/pull/359 & https://github.com/src-d/lookout/pull/375.

### CODE REVIEW

**Comment by carlosms** [comment]
ping @mcuadros for review

**Review by kuba-- — APPROVED** [review]

**Comment by carlosms** [comment]
friendly ping @mcuadros

**Comment by carlosms** [comment]
ping @mcuadros.

**Comment by mcuadros** [comment]
As I spoke in person, the `Logger` shouldn't be used as a context dictionary, for this, you should use the context itself.

**Pull request closed without merging**
